version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: etl_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-etl_mult}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-etl_mult}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
